src/modlunky2/ui/levels.py
src/modlunky2/ui/widgets.py

New Level Editor changelog:
-Fixed bug where placing a tile on very specific endgrid pixels lead to combining dual rooms/breaking the lvl
-Fixed bug where deleting tile had the deleted tile still selected/appliable
-Fixed rule table value parsing 
-Fixed incorrect textures (that I know of lmao)
-Fixed minor bug with hybrid tilecode gen
-Added ability to hold mouse down when placing tiles to essentially "paint" your levels
-Added Primary/Secondary tiles binding to your Right/Left mouse key for a better level design experience
-Tool will now load dependency lvls from extracts if they don't exist in the currently selected folder
-When loading dependency lvls in extracts mode, the tool will load the overrides version if its exists to give you a more accurate design experience
-Added ability …

Level Editor Bug Fix/Convenience Features Patch

---

src/modlunky2/ui/levels.py

Due to me changing the structure of the combobox items, "\?" was getting added to tilecodes twice, altho it's not something that would become apparent until you save and reopen the file. That's now been fixed. My apologies

Vital Bug in Tilecode gen fixed

---

src/modlunky2/ui/levels.py

Was leaving a file handle open when reading tilecodes.txt, also had PIL recreating the image object from the sprite sheet for every sprite, moved that outside the for loop so we just keep referencing the same image.

slight optimization/cleanup around the loading of sprites

---

requirements.txt
src/modlunky2/assets/assets.py
src/modlunky2/assets/string_hashing.py

This creates `stringsXX_hashed.str` files which are regular `stringsXX.str` files but every string is prefixed with it's hash of the English string (i.e. from `strings00.str`).
Users can use those files to create mods that work for sparse string modding with Playlunky.

Add hashed string files during extraction

---

src/modlunky2/ui/levels.py

New tab to automatically resolve conflicting tilecodes in sister files.
Advanced users might run into bugs I couldn't find, make backups before use. very new feature.
Files will be compared across the files they interact with. For example, opening the jungle file with have it compared to bee hive, black market, and moon challenge; although opening the moon challenge file directly will have it compared with jungle and volcana. Keep this mind when resolving your conflicts. I'd probably recommend resolving from moon challenge first, and then from jungle, in this example.
also opening generic will obviously compare across ALL files its a dependency of.
If you run into any bugs, let it be known asap. thnx.

Automatic conflicting tilecode solving

---

src/modlunky2/ui/install.py

This will rename lua script files to main.lua when installing locally or downloading from spelunky.fyi

Renaming lua script files to main.lua

---

src/modlunky2/ui/install.py
src/modlunky2/utils.py
src/tests/install/unzip_test.py

This adds UTF-8 filename support, which is not yet merged to python upstream.

Fix unicode filenames in zip

---

src/modlunky2/mem/__init__.py
src/modlunky2/ui/trackers/category.py
src/modlunky2/ui/trackers/common.py
src/modlunky2/ui/trackers/pacifist.py

This implements #121
Notably, if you close modlunky2 while a tracker window is open, there's an unhandled exception (example below). This change makes the situation more likely. I haven't looked into how to address it, and don't understand how serious this is.
```
10:32:32: Shutting Down.
10:32:32: Unhandled Exception: Traceback (most recent call last):
File "C:\Python39\lib\tkinter\__init__.py", line 1892, in __call__
return self.func(*args)
File "c:\users\mauve\dev\modlunky2\src\modlunky2\ui\__init__.py", line 394, in quit
self.root.destroy()
File "C:\Python39\lib\tkinter\__init__.py", line 2311, in destroy
for c in list(self.children.values()): c.destroy()
File "c:\users\mauve\dev\modlunky2\src\modlunky2\ui\trackers\category.py", line 142, in destroy
self.on_close()
File …
```

Instead of trackers exiting when game isn't running, wait for it

---

src/modlunky2/mem/__init__.py
src/modlunky2/mem/state.py
src/modlunky2/ui/trackers/common.py

Sometimes trackers will fail because they (seemingly) try to reattach while Spelunky 2 is shutting down. In this scenario, the `get_feedcode()` check succeeds in `_attach()` but `State.__init__()` gets `None` shortly afterwards. Example stacktrace:
```
2021-07-10 01:28:55,095: Failed in thread: Traceback (most recent call last):
File "modlunky2\ui\trackers\common.py", line 37, in run
File "modlunky2\ui\trackers\common.py", line 110, in _run
File "modlunky2\ui\trackers\common.py", line 84, in _attach
File "modlunky2\mem\__init__.py", line 333, in state
File "modlunky2\mem\__init__.py", line 328, in get_state
File "modlunky2\mem\state.py", line 119, in __init__
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
2021-07-10 01:28:55,115: Thread went away. Closing window.
```
I …

Keep trackers from dying while Spelunky 2 is shutting down

---

src/modlunky2/mem/state.py
src/modlunky2/ui/trackers/runstate.py

Apparently we get seemingly arbitrary values for the screen while Spelunky 2 is shutting down. Since this should happen infrequently, I just try to create the enum and handle the exception.  To avoid that overhead, we could use the int value, or check it before construction.

Cope with weird screen value during shutdown

---

.github/workflows/test.yml

Motivated by #132, where tests are failing to run due to an indirect dependency on Windows

Build on Windows for more accurate compatibility

---

src/modlunky2/ui/trackers/label.py
src/tests/ui/trackers/label_test.py

The only functional change is moving Eggplant relative to Abzu/Duat. There are some updates to the unit test:
- Add Pacifist CO
- Pacifist Any% to pacifist section
- Reorder tests to match their respective pages
This PR doesn't interact with the memory-reading changes at all.

Adjust Eggplant% position to match new MossRanking

---

src/modlunky2/mem/__init__.py
src/modlunky2/mem/entities.py
src/modlunky2/mem/memrauder/dsl.py
src/modlunky2/mem/memrauder/model.py
src/modlunky2/mem/memrauder/msvc.py
src/modlunky2/mem/state.py
src/modlunky2/mem_demo.py
src/modlunky2/ui/trackers/common.py
src/modlunky2/ui/trackers/pacifist.py
src/modlunky2/ui/trackers/runstate.py
src/tests/mem/memrauder/test_dsl.py
src/tests/mem/memrauder/test_model.py
src/tests/mem/memrauder/test_msvc.py

This converts `mem.entities.*` to use the Memrauder library for declarative structs, continuing the work from PR #141 ([diffs against it](https://github.com/mauvealerts/modlunky2/compare/mem-abstract-read...mauvealerts:memrauder-entity)). With this change, I think on-demand reads are limited to:
- `EntityMap` which traverses the `std::unordered_map` between instance IDs and `Entity*`
- Downcasts facilitated by `EntityWrapper` (which is new)
If we want to do more downcasting in the future, it's probably worth making `EntityWrapper` nicer and more general. Right now, we only cast to `Entity` (which could be done eagerly) and `Mount`.
Notable changes that aren't related to the migration:
- `state.players` is now `state.items.players` to better align with Overlunky. `items` can be None, since …

Convert entities to declarative structs

---

src/modlunky2/ui/trackers/label.py
src/tests/ui/trackers/label_test.py

- If we have Abzu/Duat, always hide Chain without Low%. This fixes "Chain CO" 
- Show Death% with Abzu/Duat. Sadly, the chain categories require completion
- Add some tests for intermediate chain: we have Chain SC, but don't yet have Abzu/Duat

Abzu/Duat fixes: always hide Chain w/o Low, etc.

---

src/modlunky2/mem/entities.py
src/modlunky2/mem/memrauder/model.py
src/modlunky2/mem/memrauder/msvc.py
src/modlunky2/mem/state.py
src/modlunky2/ui/trackers/category.py
src/modlunky2/ui/trackers/runstate.py
src/tests/ui/trackers/runstate_test.py

This adds `runstate_test.py`, which is ~1.5K lines and adds 295 test cases.
A few principles for the tests I wrote, to keep them manageable:
- Only test inputs that are realistic in an unmodded game
- Minimize duplication/repetition
- If a method has more than ~5 inputs, split the `test_foo` into several `test_foo_bar`, `test_foo_bat`
- Avoid lots of primitives of the same type
This PR includes some changes that aren't test cases
- Making all game state arguments of the method, to better separate it from `RunState`'s computed stuff
- Adding default values for structs, to ease test construction
- Added a `DictUnorderedMap` for use in tests
- Annotate `update_foo` method params, mostly to help me keep track of `int` vs `IntEnum`
- TODOs for bugs I noticed
- Cutting out `Spel2Proceess`, …

Add unit tests for category tracker's RunState

---

src/modlunky2/mem/entities.py
src/modlunky2/mem/state.py
src/modlunky2/ui/trackers/category.py
src/modlunky2/ui/trackers/runstate.py
src/tests/ui/trackers/runstate_test.py

This is  a hodge-podge of cleanup changes:
- Use enums consistently in dataclasses
- Pass dataclasses instead of individual values
- Remove unnecessary copying of fields into RunState
- Remove write-only fields
- Remove some attempts to skip operations that are cheap now
- Use `in` when checking for a single set element
- Fix oversight in Millionaire test

Tidy RunState a bit

---

src/modlunky2/mem/state.py

Prior to the first run in a session, the theme_start field is set to 0. There was no `Theme` enum value for 0. So, the tracker failed to update and "waiting for game..." was still displayed.

Fix "waiting for game..." before first run

---

src/modlunky2/mem/entities.py
src/modlunky2/mem/state.py
src/modlunky2/mem/testing.py
src/modlunky2/ui/trackers/common.py
src/modlunky2/ui/trackers/runstate.py
src/tests/ui/trackers/runstate_test.py

This detects whether the player teleported using the TP "shadow" effects, and only discards No TP in that case.
This detection takes advantage of several details:
- We can use `next_entity_uid` to examine only new entities
- TP shadows are created in pairs: first the "source" shadow, then the "destination" shadow
- TP shadows have an `idle_counter`, like any Movable, which is 0 on the frame of teleporting
- Combined with the above, we can use the player's velocity to extrapolate their position
There are some complications
- The shadow is always grid-aligned. However, the light is at the player's position
- ... except if the player is on a mount. Then the mount's location is used
- on active floors like Neo-Bab elevators, position and velocity are relative to the floor
False positives …

Only remove No TP when we detect teleport

---

src/modlunky2/mem/entities.py
src/modlunky2/mem/memrauder/model.py
src/modlunky2/mem/memrauder/msvc.py
src/modlunky2/mem/memrauder/spelunky2.py
src/modlunky2/mem/state.py
src/modlunky2/mem/testing.py
src/modlunky2/ui/trackers/runstate.py

As far as I know, there are two things preventing this from being releasable
* Updating entity type IDs
* More thoroughly testing entity lookup
For entity lookup testing, I currently have it both do the lookup the hash way, and also a full table scan. Mismatches are logged. My other ideas are:
* Check if we actually probe multiple entries in the hash version
* Do a full scan and do the fast lookup for every entry

Tracker updates for version 1.23x

---

requirements.txt
src/modlunky2/config.py

Note: there's an undocumented change in behavior on macOS: `user_config_dir()` returns a path under `Library/Preferences` instead of `Library/Application Support`.
I noticed this fork via `black`'s changelog.

Move from unmaintained appdirs to platformdirs

---

src/modlunky2/ui/trackers/label.py
src/modlunky2/ui/trackers/runstate.py
src/tests/ui/trackers/runstate_test.py

Notably, runs now start as either "No%" or (with early modifiers) "Pacifist No%" at 1-1. From Ice Caves, they now start as "Pacifist Ice Caves Shortcut No%"

Add support for No%  to cat tracker

---

src/modlunky2/ui/install.py

If the mod has a save.dat file, it will be copied to a temporary directory (named temp_fyi.{install_code}) and copied back into the pack directory after the new version of the pack has been downloaded.

Preserve save files when updating a mod through the Modlunky UI

---

src/modlunky2/mem/__main__.py
src/modlunky2/mem/arena_state.py
src/modlunky2/mem/memrauder/model.py
src/modlunky2/mem/state.py
src/tests/mem/memrauder/test_model.py

* Populates all user configurable fields for arena for saving off to a config file.
* Added some debug printing in mem.__main__ to verify it round trips and prints as expected.
* Updated unwrap_tuple_type to allow for homogeneous n-tuples as pyserde doesn't like ellipsis.

Add memory reader for Arena structures

---

src/modlunky2/config.py
src/modlunky2/ui/trackers/category.py
src/modlunky2/ui/trackers/common.py
src/modlunky2/ui/trackers/label.py
src/modlunky2/ui/trackers/pacifist.py
src/modlunky2/ui/trackers/runstate.py

The user-visible parts of this change are
* Per-tracker configs (e.g. "Always Show Modifiers") are now persisted between runs of modlunky2
* Per-tracker config changes are applied on next poll, instead of requiring restarting the tracker
There are a couple warts:
* Color key changes aren't applied immediately
* If modlunky2 is downgraded, the per-tracker configs are lost
Notable internal changes:
* Unified `WatcherThread` and `TrackerWindow` implementations
* New `Tracker` interface for per-tracker bits
* Pacifist tracker now updates every 16ms (vs 100ms)
* Data shipped between `WatcherThread` and `TrackerWindow` is now in dataclasses (vs dicts)

Persist per-tracker configs and apply them immediately

---

.github/workflows/build-exe.yml
CONTRIBUTING.md
README.md
requirements-dev.txt

Since a lot's moved around, here's my attempt at a list of changes...
* General tidying based on markdownlint
* Readme
* Remove pypi badge 
* Outline various things Modlunky2 does
* Remove partial installation and usage instructions, in favor of wiki link
* Abbreviate disclaimer
* Move development info to a separate Contributing page
* Contributing
* Add pointers to Discord
* Suggest looking at bugs before filing new ones
* Suggest discussing changes
* Setup tweaks
* List Windows venv commands first
* Remove shell prompts from console bits
* Recommend VS Code
* Remove wheel instructions
* Building exe 
* Point to GitHub actions
* Mention Rust
* Shove "custom pyinstaller" and dll under "Troubleshooting"
* requirements-dev.txt
* include pyinstaller
* remove twine

Expand and update documentation

---

src/modlunky2/config.py
src/modlunky2/ui/trackers/category.py
src/modlunky2/ui/trackers/label.py
src/modlunky2/ui/trackers/runstate.py
src/tests/ui/trackers/label_test.py

Adds checkboxes to the category tracker that disables the visualization of all non-terminal starting categories, i.e., all of them except Any%.
Mainly because Hectique asked for it and I was bored.
Ran the unit tests and tested it for a while. Seems fine.

Allow Excluding Starting Categories

---

src/modlunky2/sprites/floor_sheet.py

The surface texture sheet does not have a push block texture, so we have to remove it from the chunk map to allow the default push block texture to be used.

Fix missing push block texture when in the surface theme.

---

src/modlunky2/ui/levels/tab.py

CTRL+S works from _anywhere_ (including tabs other than the level editor), but it doesn't seem to cause errors (?)

[Level editor] Add CTRL+S shortcut for saving

---

src/modlunky2/ui/levels/tab.py

I guess python doesn't return nil if a dictionary doesn't contain the key.

Properly check that the default tile codes exist in a way that doesn't cause a python error.

---

src/modlunky2/ui/levels/tab.py

These lines are a separate color to make it easy to tell where the rooms end when using mechanics that depend on the room such as switches.
This also includes a slight refactoring of the options menu to use a state var to keep track of the row instead of hard coding the row, to make it easier to insert options in the future.

Add lines to the grid at room boundaries.

---

src/modlunky2/ui/levels/tab.py

Fix the drawn offsets of several enemies so that they are drawn in the editor in the same position they spawn in the game.
Also fixed some code for draw mode 8 even though that one isn't being used; at least it matches the documentation now.
And fixed some of the comments.

Fix the drawn offsets of several enemies

---

src/modlunky2/category/chain/common.py
src/modlunky2/mem/entities.py
src/modlunky2/mem/memrauder/model.py
src/modlunky2/mem/memrauder/spelunky2.py
src/modlunky2/ui/trackers/label.py
src/modlunky2/ui/trackers/runstate.py
src/tests/mem/memrauder/test_dsl.py
src/tests/mem/memrauder/test_model.py
src/tests/ui/trackers/runstate_test.py

Visible changes
* Update clover rule for low%
* Add support for Volcana/Temple
* Chain Low% hides Jungle/Temple and Volcana/Temple
* Fix naming of Chain No% Abzu/Duat
I also did some typing cleanup while I was in the area. The big change is `PolyPointer` no longer has a weird 'empty' version. That simplifies checks and makes the `value` a plain value (vs `Optional`).
Other typing tweaks:
* Pyright doesn't like it when a variable has an explicit type and an incompatible one is assigned to it
* `Optional[Foo]` is not assignable to `Type[Any]` because `UnionType` is not assignable to `Type` (because `Union` can't be instantiated / isn't callable)

Tracker low% updates

---

src/modlunky2/config.py
src/modlunky2/ui/levels/tab.py

pyserde 0.6.0 added a `field()` function that wraps `dataclasses.field()`. We can use it to tidy config.py substantially.
That release also added `@serde`, which applies `@deserialize`, `@serialize`, and `@dataclass`. However, I'm not including it here. I'm seeing behavior changes and haven't debugged why. It's also slightly less helpful because it 'hides' `@dataclass` from type checkers; I hope to apply `@dataclass_transform` ([PEP 681](https://www.python.org/dev/peps/pep-0681/), available in `typing_extensions`) in another change (preferably upstream) to make it prettier.
I've also refactored the "custom level editor" config to use pyserde. I think it simplifies the code a lot. I'm a bit worried about errors in the refactoring... I split it into two commits:
* Use pyserde instead of …

Improve config file stuff

---

src/modlunky2/config.py
src/modlunky2/ui/extract.py
src/modlunky2/ui/install.py
src/modlunky2/ui/play/controls.py
src/modlunky2/ui/play/pack.py
src/modlunky2/ui/play/packs.py
src/modlunky2/ui/play/play.py
src/modlunky2/ui/settings.py
src/modlunky2/utils.py

This should fix #261 and hopefully fix some other latent bugs.
Notably, I've left a bunch of the packs code in its current state because it looks like packs usually shouldn't exist without `install_dir` set. I also suspect there's deeper issues if `install_dir` is set to `None` during a Pack object's lifetime.

Handle unset install-dir better

---

requirements.txt
src/modlunky2/cli.py
src/modlunky2/config.py
src/modlunky2/web/api/framework/multiplexing.py
src/modlunky2/web/api/framework/pubsub.py
src/modlunky2/web/api/framework/serde_tag.py
src/modlunky2/web/api/framework/session.py
src/modlunky2/web/demo.py
src/modlunky2/web/service.py
src/tests/conftest.py
src/tests/web/api/framework/multiplexing_test.py
src/tests/web/api/framework/pubsub_test.py
src/tests/web/api/framework/serde_tag_test.py
src/tests/web/api/framework/session_test.py

I think this is at a reasonable milestone to start merging in (or close to it)
* Starts a server on port 9526 (edit: now configurable in `config.json` via `api-port`)
* "Tagged" messages, currently `{"SomeTypeName": {"some_field": True}}`
* Multiplexed dispatch of incoming messages, based on their type
* Clients choose their own session ID, baked into the path
* Just used to simplify internals a bit
* Server will reject connections if the session ID is currently in-use
* Simple PubSub system
* No persistence or reconnect support
* Client sends
* `{"Subscribe": {"topics": ["Foo", "Bar"]}}`
* `{"Unsubscribe": {"topics": ["Foo", "Bar"]}}`
* Server sends `{"Published": {"Foo": {"widgets": 3}}}`
* Python API differentiates between priorities, delivers messages in-order
* May drop -- Not …

Add Web Service w/ WebSocket API

---

src/modlunky2/category/chain/sunken.py
src/tests/category/chain/sunken_test.py

The Ankh is removed when the player is stunned on the Altar in CoG. Apparently there are frames where they don't have Ankh and the sacrifice hasn't finished (i.e. there's still a player).
This fix removes that awkward time window, while still detecting non-altar death. We could check more stuff (e.g. `standing_on` altar) but this seems sufficient. Notably, the player is revived in a standing state

Continue chain when missing Ankh & stunned in CoG

---

src/modlunky2/ui/trackers/label.py
src/tests/ui/trackers/label_test.py

Eggplant and Death had same 'percent' priority. This disambiguates the case.

Fix tracker crash on eggplant+death

---

src/modlunky2/web/api/framework/multiplexing.py
src/modlunky2/web/api/framework/session.py
src/modlunky2/web/service.py
src/tests/web/api/framework/session_test.py

Since WebSocket doesn't apply SOP (Same Origin Policy) and doesn't implement CORS, it's possible for any website to open a connection to Modlunky2. This validates the origin, if present, is from a localhost-like origin. If the origin header isn't present, we assume it's a local process and therefore OK.
Originally, I was going to add a check that the origin matched the service itself. However, that wouldn't work with the current UI served by Node.JS; it seems desirable to keep that working.
I considered adding a flag to allow-list additional origins, but it seems more error-prone and would require plumbing the value through. OTOH, checking for various localhost-like origins was more complicated than I expected.

Add origin check to websocket API

---

src/libs/ml2_mods/src/data.rs
src/libs/ml2_mods/src/manager.rs

I suspected that `#[tauri::command]` will require errors are `serde::Serialize`, and indeed it does. I'm not sure this is worthwhile (vs just using `String`), but it makes it possible for the frontend to identify the error-variant.
Example
```
let e = Error::ModExistsError("hi".to_string());
println!("{}", serde_json::to_string(&e)?);
```
Outputs `{"ModExistsError":"Mod hi already exists"}`

Make mod manager errors serialize nicely

---

Cargo.lock
src/libs/ml2_mods/Cargo.toml
src/libs/ml2_mods/examples/mods.rs
src/libs/ml2_mods/src/local.rs
src/libs/ml2_mods/src/manager.rs
src/libs/ml2_mods/src/spelunkyfyi/http.rs
src/libs/ml2_mods/src/spelunkyfyi/mod.rs
src/libs/ml2_mods/src/spelunkyfyi/poll.rs
src/libs/ml2_mods/tests/manager.rs

Some notes
* I expect the "updates" channel will also be used for other stuff (e.g. when mod installed via webchannel)
* I'm not happy about the cyclic data flow (poller → manager → poller) but it's probably fine
* `ModManagerHandle::duplicate()` dance is working around `broadcast::Receiver` being `!Clone`
* Similarly poll objects use `Notify` so `PollerHandle` can be `Clone`
* `Poller::run` method is a little tricky because it tries to be responsive to shutdown requests
* We wait a random amount of time between fetches. This is partially to be nice to the server if there's a lot of mods to poll, but also to defer to UI requests.
* I ditched `ManifestParseError` in favor of making all JSON errors into `UnknownError`; hard to imagine the client doing much with them

Implement writing latest.json and polling for updates

---

Cargo.lock
src/launcher/Cargo.toml
src/launcher/src/main.rs

This is prompted by the Clap 4.x release, which removes deprecated functionality
* Update edition to 2021
* Fix clippy lint
* Replace clap::App with clap::Command
* Migrate from `AppSetting` with various `Command` methods
* Use shiny new `Arg::action` method
* Switch to Clap 4, with remaining updates that couldn't be applied to Clap 3

Tidy the ol' Launcher, upgrade to Clap 4

---

.github/workflows/build-exe.yml
.github/workflows/rust-test.yml
.github/workflows/test.yml
.github/workflows/ui-test.yml

Bump action versions, motivated by deprecation warnings.
This also moves UI testing from Node 16 to 18

Actions updates

---

.github/workflows/rust-test.yml
Cargo.toml
deny.toml
src/launcher/Cargo.toml
src/libs/ml2_assets/Cargo.toml
src/libs/ml2_chacha/Cargo.toml
src/libs/ml2_entity_data/Cargo.toml
src/libs/ml2_mods/Cargo.toml
src/libs/ml2_net/Cargo.toml
src/libs/ml2_types/Cargo.toml
src/libs/ml2_vorbis_header/Cargo.toml
src/tauri/src-tauri/Cargo.toml

This sets up [cargo deny](https://embarkstudios.github.io/cargo-deny/index.html) to check:
* All crates have a compatible license
* No crates have security advisories
* All crates come from crates.io
I started fiddling with it mostly for `cargo deny check bans`, which can check for multiple versions of the same crate. The other functionality seems nice to have though, and more reasonable to enforce.
Re: licensing: most of the allow-list is for single crates. MPL-2.0 is the only one used by several, and the only copyleft one (albeit minimally copyleft). I elected to deny copyleft, since most conflict with the spirit of Apache 2.0 license. I don't feel strongly about it, though.

Cargo deny

---

src/launcher/build.rs
src/launcher/src/main.rs
src/libs/ml2_assets/src/bin/extract-soundbank.rs
src/libs/ml2_assets/src/strings.rs
src/libs/ml2_assets/src/vorbis_data/rebuild.rs
src/libs/ml2_mods/examples/api.rs
src/libs/ml2_mods/examples/mods.rs
src/libs/ml2_mods/src/data.rs
src/libs/ml2_mods/src/local/disk.rs
src/libs/ml2_mods/src/manager.rs
src/libs/ml2_mods/src/spelunkyfyi/http.rs
src/libs/ml2_mods/src/spelunkyfyi/web_socket.rs
src/libs/ml2_mods/tests/manager.rs

This has been available [since 1.58](https://caniuse.rs/features/format_args_capture) and clippy will complain in 1.66 ([demo](https://play.rust-lang.org/?version=beta&mode=debug&edition=2021&gist=30a62696edbc5c7cb6bb6f286f664fc8)). Note that this isn't as powerful as f-strings in Python: neither expressions nor field access are supported

Inline formatting params

---

src/modlunky2/config.py
src/modlunky2/ui/overlunky.py
src/modlunky2/ui/play/options.py
src/modlunky2/ui/play/play.py

Better late than never to fix more things in tk version.
This depends on both https://github.com/spelunky-fyi/overlunky/pull/283 and https://github.com/spelunky-fyi/Playlunky/pull/40 to roll out first.

Fix empty Overlunky console and add new launcher options

---

src/tauri/src/lib/pages/playlunky/EnabledMods.svelte
src/tauri/src/store.ts
src/tauri/vite.config.ts

Using the `mods` array for the dnd, when the only movable mods where the enabled ones caused some issues. This fixes it by making `enabledMods` a writable, so it works with the dnd, and gets updated every time `mods` change, while preserving the order.
I guess another solution would be to save the mod order in some variable and just filter and sort `mods` to update `enabledMods`.
Also, should `enabledMods` hold a copy of the mods, or just a reference like what I did?

Fix enabled mods drag-n-drop (tauri)

---

src/modlunky2/ui/play/pack.py

This mitigates a problem [reported on Reddit](https://www.reddit.com/r/spelunky/comments/14zr3ho/problems_with_modlunky/) where an error loading the image prevents the entire Playluynky tab from loading. Presumably this is because the image is corrupt (or a bug in Pillow).
This PR doesn't offer a way to redownload the image, but at least they can find out which pack needs to be reinstalled.

Catch exceptions when loading mod logos

---

src/modlunky2/sprites/base_classes/base_sprite_merger.py
src/modlunky2/sprites/sprite_fetcher.py

* Correct size calculation. Might not matter in practice, but I found a [migration example](https://pillow.readthedocs.io/en/stable/releasenotes/9.2.0.html) and it seems worth fixing while we're here
* Replace uses of `textsize` with `textbbox`. In addition to the bounding box change, it also takes a new position parameter

More Pillow 10 fixes/tweaks

---

src/modlunky2/levels/level_settings.py
src/modlunky2/mem/memrauder/model.py

I'm not sure what caused pylint to be more strict here, since all checks passed on each PR. Anyway... this seems to make it happy enough. Making a PR to verify fixes work across Python versions

Tweak type annotations for pylint

---

Cargo.lock
src/libs/ml2_mods/Cargo.toml
src/libs/ml2_mods/src/spelunkyfyi/web_socket.rs

Tungstenite, and therefore tokio-tungstenite, had some notable API changes:
* Buffers are now in terms of bytes
* Implicit flushes have generally been removed
The default send buffer is 128KiB, which seems more than enough for our needs. Note that writes will fail if the buffer is full, but I'd wrather do that than consume unbounded memory. Also we flush a lot, maybe too much.
Generally, the websocket stuff could probably use some more thought. This is just enough to keep it working roughly the same.

Upgrade tokio-tungstenite

---

src/modlunky2/ui/trackers/gem.py
src/modlunky2/ui/trackers/pacino_golf_tracker.py

Going from Tiamat to Sunken City does two extra level transitions (6-4 => 6-1 => 6-4 => 7-1).
This adds the number of gems collected in Tiamat twice (even to the yem counter). [(Video of bug)](https://www.twitch.tv/videos/1995902836?t=02h51m55s)
These are now excluded (they have the BASE_CAMP theme).

Fix Olmec Ship cutscene gem tracker issue

---

src/modlunky2/config.py
src/modlunky2/ui/levels/custom_levels/custom_level_editor.py
src/modlunky2/ui/levels/shared/level_canvas.py
src/modlunky2/ui/levels/shared/multi_canvas_container.py
src/modlunky2/ui/levels/shared/palette_panel.py
src/modlunky2/ui/levels/shared/setrooms.py
src/modlunky2/ui/levels/vanilla_levels/levels_tree.py
src/modlunky2/ui/levels/vanilla_levels/multi_room/multi_room_editor_tab.py
src/modlunky2/ui/levels/vanilla_levels/multi_room/options_panel.py
src/modlunky2/ui/levels/vanilla_levels/multi_room/reversed_rooms.py
src/modlunky2/ui/levels/vanilla_levels/multi_room/room_map.py
src/modlunky2/ui/levels/vanilla_levels/multi_room/template_draw_item.py
src/modlunky2/ui/levels/vanilla_levels/vanilla_level_editor.py
src/modlunky2/ui/levels/vanilla_levels/vanilla_types.py

Replaces the full level viewer tab with a full level editor that allows editing of multiple rooms in a level at once.
- Creates a canvas with all of the setrooms for editing for any level with setrooms.
- Creates a canvas with path rooms for any level with path rooms.
- Creates a canvas with side and miscellaneous rooms laid out in a grid for simultaneous editing.
The map of rooms in each canvas can be configured to edit any rooms together.
For any room being edited, can select which chunk of the room to edit, and can edit multiple chunks of the same room template at once.

Replace the full level viewer with a full level editor

---

src/modlunky2/ui/levels/custom_levels/custom_level_editor.py
src/modlunky2/ui/levels/shared/palette_panel.py

- For the first ten tiles in the palette, press a _number key_ to set the primary tile or _alt + number key_ to set the secondary tile.
Inspired by https://github.com/spelunky-fyi/modlunky2/issues/78 but does something different. Would be even more useful with https://github.com/spelunky-fyi/modlunky2/issues/64.
- Also fixes tile-deletion-buttons being disabled after clicking them

[Level editor] Add keyboard shortcut for selecting tiles

---

src/modlunky2/ui/levels/shared/create_template_dialog.py
src/modlunky2/ui/levels/vanilla_levels/level_list_panel.py
src/modlunky2/ui/levels/vanilla_levels/levels_tree.py
src/modlunky2/ui/levels/vanilla_levels/multi_room/multi_room_editor_tab.py
src/modlunky2/ui/levels/vanilla_levels/multi_room/options_panel.py
src/modlunky2/ui/levels/vanilla_levels/multi_room/room_map.py
src/modlunky2/ui/levels/vanilla_levels/vanilla_level_editor.py

Adds a button to both the room list in the single-room editor and the room type selection dropdown in the multi-room editor to create a new room.
The new room type can be created with any width and height, and it is up to the level creator to make sure it works in game.
The new room type cannot be created with the same name as an existing room type.
Also, a minor improvement was added so that selecting a room type doesn't clear the canvas of the currently editing room; only selecting another room will.

Add a button to create a new template of rooms

---

src/modlunky2/ui/levels/custom_levels/custom_level_editor.py
src/modlunky2/ui/levels/shared/palette_panel.py
src/modlunky2/ui/levels/shared/tile.py
src/modlunky2/ui/levels/vanilla_levels/multi_room/multi_room_editor_tab.py
src/modlunky2/ui/levels/vanilla_levels/vanilla_level_editor.py

Split tilecodes from dependencies into separate palettes so that they aren't automatically added to the level file when saving, but are still available in the palette to select.

Split tilecodes from dependencies into separate palettes

---

src/modlunky2/ui/levels/custom_levels/create_level_dialog.py
src/modlunky2/ui/levels/custom_levels/custom_level_editor.py
src/modlunky2/ui/levels/shared/palette_panel.py
src/modlunky2/ui/levels/shared/tile.py
src/modlunky2/ui/levels/vanilla_levels/vanilla_level_editor.py
src/modlunky2/ui/levels/vanilla_levels/variables/dependencies_tree.py
src/modlunky2/ui/levels/vanilla_levels/variables/level_dependencies.py
src/modlunky2/ui/levels/vanilla_levels/variables/variables_tab.py

Fixes variables tab to only show conflicts between the current file and its dependencies/dependants, and only apply fixes by modifying the current file instead of attempting to change every other file that conflicts with it.
This also hopefully fixes the resolve conflicts button breaking levels, since the resolving conflicts logic is simpler and makes sense now.
Some other changes are also included which help avoid conflicts being introduced in the first place, or fix related logic.

Fix variables tab in level editor

---

src/modlunky2/ui/trackers/co_tracker.py

I used Counter.total which was only added in python 3.10. (oops)

Fix Counter to work pre-python-3.10
