spelunky-fyi/modlunky2

- src/modlunky2/ui/levels.py
- src/modlunky2/ui/widgets.py
-Fixed bug where drawing out of bounds on canvases caused visual issues
-Fixed new placed tiles not anchoring properly
-Fixed Tiamats bg to Babylon like it should have been
-Fixed Tile pallet not being fully docked
-Re-organized checkboxes in a way that made more sense
> Bug Fix Update

- src/modlunky2/ui/trackers/category.py
- src/modlunky2/ui/trackers/common.py
- src/modlunky2/ui/trackers/pacifist.py
Before embarking on this quest,  I looked into a couple alternatives:
- Font picker+styling. There is no built-in font picker (though `tkfontchooser` exists) and tkinter styling seems limited. In particular it's not obvious how to implement outlines, which seems desirable for overlays.
- Web page. This would obviously involve adding a server along with some HTML and a small JS script/app. It seems more reasonable, but also a bunch more effort.
The text file approach has a some downsides:
- It's easy to end up with stale file info. I've tried to handle the obvious cases.
- It's not obvious what a good default location is. I shoved it in `DATA_DIR`, but that's inside a hidden folder (AppData).
- OBS only reads the updated contents of a "text source" file at most once a second. This will lag …
> Make trackers write to a file

- src/modlunky2/ui/trackers/category.py
- src/modlunky2/ui/trackers/common.py
This fixes #123 as well as the exception I noticed while working on #122
> Close trackers more gracefully

- src/modlunky2/ui/trackers/runstate.py
> Display modifiers on score screen and Hundun win implies SC%

- src/modlunky2/ui/trackers/runstate.py
[per Hectique](https://discord.com/channels/150366712775180288/758716867572531220/864842434026537031) in s2-rule-discussion
> Allow curing status effects via ankh

- src/modlunky2/ui/trackers/runstate.py
I implemented a whole ankh→revive→dead state thing before noticing you still have the ankh during the revive animation 🙃
> We're not really dead if we're reviving

- src/modlunky2/mem/entities.py
- src/modlunky2/mem/state.py
- src/modlunky2/ui/trackers/label.py
- src/modlunky2/ui/trackers/runstate.py
I almost gave up on the score check, tbh. I didn't expect to need to check three numbers, and miscalculated a memory offset at one point.
> Millionaire support for tracker, via score or clone gun

- src/modlunky2/ui/install.py
For installing multiple mods without using the mouse
> Accept enter key in install code field

- requirements.txt
- src/modlunky2/config.py
Now with 50% more pyinstaller hinting!
> Migrate from unmaintained appdirs to platformdirs

- src/modlunky2/mem/testing.py
- src/modlunky2/ui/trackers/runstate.py
- src/tests/ui/trackers/runstate_test.py
I'm investigating ways to detect usage mid-level, but this seems like a worthwhile start
> Correct No% rope checks

- requirements.txt
- src/modlunky2/cli.py
- src/modlunky2/config.py
- src/modlunky2/ui/__init__.py
- src/modlunky2/ui/extract.py
- src/modlunky2/ui/install.py
- src/modlunky2/ui/levels.py
- src/modlunky2/ui/overlunky.py
- src/modlunky2/ui/pack.py
- src/modlunky2/ui/play/controls.py
- src/modlunky2/ui/play/options.py
- src/modlunky2/ui/play/pack.py
- src/modlunky2/ui/play/packs.py
- src/modlunky2/ui/play/play.py
- src/modlunky2/ui/play/releases.py
- src/modlunky2/ui/s99.py
- src/modlunky2/ui/settings.py
- src/modlunky2/ui/trackers/category.py
- src/modlunky2/ui/trackers/options.py
- src/modlunky2/ui/trackers/pacifist.py
- src/modlunky2/ui/websocket.py
- src/modlunky2/ui/widgets.py
- src/tests/config_test.py
This should be equivalent to the old implementation, with the exception of flag changes:
* Remove `--install-dir` and `--beta`
* Add `--config-file`
It's a pretty invasive refactor, so I intend to persist tracker settings in a later change.
> Collapse ConfigFile into Config, use pyserde to serialize

- src/modlunky2/ui/levels/tab.py
Adds a size parameter to the level settings with the "width, height" of the level like vanilla levels use.
> Save the level size in the level settings.

- src/modlunky2/sprites/floorstyled_sheet.py
Same as this change to Temple: https://github.com/spelunky-fyi/modlunky2/commit/9e3725dc85f2dd414fcdca7d31307d62e2ea679c
> Change CoG and Duat floor texture in level editor to differentiate it from push block

- src/modlunky2/ui/levels/tab.py
Write all expected vanilla setrooms of an area instead of just writing the setrooms for rooms that exist in the current size of the level.
> Write all expected vanilla setrooms of an area

- .github/workflows/build-exe.yml
- Cargo.lock
- Cargo.toml
- build-exe.py
I expect the mods library will need a more thorough review, so I broke this out into a separate PR. Not sure it's worthwhile, but it also seems relatively harmless
> Configure Cargo workspaces

- .github/workflows/build-exe.yml
- .github/workflows/rust-test.yml
- .github/workflows/test.yml
- .github/workflows/ui-test.yml
Marking this as a draft while I test it
> GitHub workflow tweaks

- src/modlunky2/ui/levels/tab.py
Did another oopsie on last PR, sorry
> Don't show _all_ level files in the ARENA folder

- src/modlunky2/ui/trackers/label.py
- src/modlunky2/ui/trackers/runstate.py
- src/tests/ui/trackers/label_matches_mr_test.py
> ICS no longer implies Low%

- .github/workflows/build-exe.yml
- .github/workflows/rust-test.yml
- .github/workflows/ui-test.yml
actions-rs is apprently unmaintained
> Switch from actions-rs to dtolnay/rust-toolchain

- src/modlunky2/ui/play/play.py
> Fix load order file not opening as utf-8

- src/tauri/src/lib/common/Button.svelte
- src/tauri/src/lib/pages/playlunky/ModListItem.svelte
- src/tauri/src/lib/pages/playlunky/ModListItemDragHandle.svelte
This would fix the issue of the mods not being dragged when pressing on the padding of the drag handle
> Change ModListItem drag button to div

- src/modlunky2/config.py
- src/modlunky2/mem/state.py
- src/modlunky2/ui/__init__.py
- src/modlunky2/ui/trackers/category.py
- src/modlunky2/ui/trackers/common.py
- src/modlunky2/ui/trackers/options.py
- src/modlunky2/ui/trackers/pacifist.py
- src/modlunky2/ui/trackers/timer.py
- Add all IL times option to timer tracker
- Add slider to change tracker font size
- Add combobox to change tracker font family
- Make session timer more accurate by only using ingame frames for init and append real time to that
> More tracker stuff

- src/modlunky2/ui/levels/custom_levels/create_level_dialog.py
The dialog is still creating tiles as an array of data instead of using the Tile
> Fix add level dialog not creating the new level
